name: Call a reusable workflow

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/5 * * * *"

jobs:
  call-workflow:
    uses: mlubej/github-actions-test/.github/workflows/reusable_workflow.yml@develop