name: Reusable workflow example

env:
  # The only way to simulate if-else statement
  CHECKOUT_BRANCH: ${{ github.event_name == 'schedule' && 'develop' || github.ref }}

on:
  workflow_call:

jobs:
  my-custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: test action
        run: |
          echo "running on develop"
          echo ${ls -l ./}
