name: Reusable workflow example

on:
  workflow_call:

jobs:
  my-custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name and list files
        run: |
          echo "running github-action on main"
          echo "checked out branch: ${{ github.ref }}"
          echo "list checked out files: below"
          python -c 'import os; os.system("ls -l ./")'
