name: Reusable workflow example

env:
  # The only way to simulate if-else statement
  CHECKOUT_BRANCH: ${{ github.event_name == 'schedule' && 'develop' || github.ref }}

on:
  workflow_call:

jobs:
  my-custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Echo branch name and list files
        run: |
          echo "running github-action on main"
          echo "checked out branch: ${{ env.CHECKOUT_BRANCH }}"
          echo "list checked out files: below"
          python -c 'import os; os.system("ls -l ./")'