name: Reusable workflow example

on:
  workflow_call:

jobs:
  my-custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Echo branch name and list files
        run: |
          echo "running github-action on develop"
          echo "checked out branch: ${{ github.ref }}"
          echo "list checked out files: below"
          python -c 'import os; os.system("ls -l ./")'

  mirror-and-integration-test-on-gitlab:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
            args: "https://git.sinergise.com/eo/github-actions-test.git"
        env:
            FORCE_PUSH: "true"
            GITLAB_HOSTNAME: "git.sinergise.com"
            GITLAB_USERNAME: "github-action"
            GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
            GITLAB_PROJECT_ID: "1136"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

