name: Reusable workflow example

env:
  # The only way to simulate if-else statement
  CHECKOUT_BRANCH: ${{ github.event_name == 'schedule' && 'develop' || github.ref }}

on:
  workflow_call:

jobs:
  my-custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Echo branch name
        run: |
          echo "running on develop ${{ env.CHECKOUT_BRANCH }}"

      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.1
        with:
          repo: ${{ github.repository }}
          ref: ${{ env.CHECKOUT_BRANCH }}
          path: "."
          ext: ".txt"
